### ISSUE TITLE
Last waypoint missing from csv

### ISSUE THREAD

**Issue by sgraham3** [YarostheLaunchpadder/MissionPlanner-to-Litchi#29]
Not sure if iam missing a setting or not under standing what is happen but when I create the csv file the last waypoint in missing. I see in the documents MP_trigger_dist.md it looks like the same thing happened. waypoint 20 is missing from mission hub. I was able make a duplicate of the last waypoint then it is correctly imported.

**Comment by JoeKae** [comment]
Could you please provide us with the input file so that we can attempt to replicate the issue?

**Comment by sgraham3** [comment]
[missingwp.waypoints.log](https://github.com/YarostheLaunchpadder/MissionPlanner-to-Litchi/files/11960200/missingwp.waypoints.log)
[missingwp.waypoints.csv.log](https://github.com/YarostheLaunchpadder/MissionPlanner-to-Litchi/files/11960201/missingwp.waypoints.csv.log)

**Comment by JoeKae** [comment]
Thank you for your response. I will review it over the weekend.

**Comment by JoeKae** [comment]
The problem occurred due to an empty line at the end of the waypoints file. This issue has been resolved in the most recent release (1.1.1), which can be found at [this link](https://github.com/YarostheLaunchpadder/MissionPlanner-to-Litchi/releases/tag/v1.1.1).

We appreciate you bringing this to our attention.
