### ISSUE TITLE
Mission Planner to Litchi crashing on win11

### ISSUE THREAD

**Issue by Nguyentunnel** [YarostheLaunchpadder/MissionPlanner-to-Litchi#5]
I open MPTL on desktop and the .waypoints is on desktop too. 

I input the filename include .waypoints and the exe closes out everytime. 

Could this be a win11 issue perhaps? 

I have reinstalled and tried a few files from mission planner with the same issue.

**Comment by YarostheLaunchpadder** [comment]
Can you please run it from the command line and post the error here?

**Comment by Nguyentunnel** [comment]
When I run it from command I have the same issue but no error in command. 

made a quick video showing you what I experience 

https://www.loom.com/share/ea1c12cdeb7446b9a24890d050f77587

**Comment by YarostheLaunchpadder** [comment]
Don't use the start command in the command prompt, just type the name of the exe directly and press enter, that way it opens directly in the CMD instead of a new window, so when it crashes, it will also output the error into the same CMD window.

**Comment by Nguyentunnel** [comment]
![Screenshot 2022-08-13 204436](https://user-images.githubusercontent.com/110569652/184519239-d5ddfd9f-22f8-4c36-a18b-c17b830cee15.png)

ok thank you. Here you go.

**Comment by YarostheLaunchpadder** [comment]
Okay, this is an issue that happens when you sync your Desktop folder with OneDrive. My script can't properly find the desktop, as its real location is on OneDrive in the cloud.
The solution for now is run a modified version of the script, which saves the CSV file in the same location as the script itself is ran from. Try to run it on the desktop, if it doesn't work, then  run it in the root folder of your C Drive with Admin Access.

Here is the modified EXE file: https://drive.google.com/file/d/1SQPq3Y2pNra9MknPmCCAoLEzIgbvrC-X/view?usp=sharing

**Comment by Nguyentunnel** [comment]
ok now its working. Thank you!
